### ISSUE TITLE
Compat for Create: Steam & Rails

### ISSUE THREAD

**Issue by BLOKBUSTR** [Itsyourdriver/unpackable-minecarts#1]
I have already copied and modified some functions to support unpacking of a couple new minecarts provided by [Create: Steam 'n' Rails](https://modrinth.com/mod/create-steam-n-rails). These carts include Crafting Tables and Jukeboxes. I wanted to discuss these additions in an issue first rather than coming out of the blue with a PR lol (especially since I have never performed a PR yet)

https://github.com/Itsyourdriver/unpackable-minecarts/assets/118950712/3bcd62f8-5b7d-40fa-8315-5ad3a1d94cc9

I made all these new functions still under the `minecartcrafting` namespace. I decided to name my own functions in accordance with the minecart variants themselves, like `benchcart` and `jukeboxcart`, primarily to avoid confusion for myself.

Also, would it be possible to hide the recipe unlock toasts without breaking the advancement functions? I've tried setting `show_toast` to false, but for some reason the recipe just gives me the Knowledge Book item without triggering the associated function... The JSON formatting was completely fine too, yet this issue persisted even after reverting my changes. I'm not adept with scripting datapacks yet, so I don't know if there's something I'm doing wrong.

**Comment by Itsyourdriver** [comment]
> Also, would it be possible to hide the recipe unlock toasts without breaking the advancement functions? I've tried setting show_toast to false, but for some reason the recipe just gives me the Knowledge Book item without triggering the associated function... The JSON formatting was completely fine too, yet this issue persisted even after reverting my changes. I'm not adept with scripting datapacks yet, so I don't know if there's something I'm doing wrong.

I'll mess around with it when I get the chance, I already have plans to clean up the pack soon so it's a good place to start.
Do you have the datapack files with your version so I can take a look at them?

**Comment by BLOKBUSTR** [comment]
I can fork this repository real quick, then drop all my new files in there for you to see. Shouldn't take too long 👍

**Comment by BLOKBUSTR** [comment]
Aight, here it is: https://github.com/BLOKBUSTR/unpackable-minecarts_compat-wip

I've named the functions according to the mod IDs and whatever blocks are being unpacked from the minecarts.

**Comment by Itsyourdriver** [comment]
Just got around to testing and I see what you mean, the main problem is that there is no `show_toast` for recipes. I tried it on the advancement which changed nothing. I also see that the chest minecart function is broken which is what you were experiencing with it persisting. Currently trying to figure out that function.

**Comment by Itsyourdriver** [comment]
@BLOKBUSTR Sorry for the insanely long wait, but I finally got everything working again and I'll be getting an update out very soon. (assuming it works on 1.21 fine) Thank you so much for getting this more cleaned up version of the pack done, it's made everything much easier to maintain lol

**Comment by Itsyourdriver** [comment]
I'm going to close this but if you have anything more feel free to let me know

**Comment by BLOKBUSTR** [comment]
You're welcome! And no worries about the delay. I'll check out the update within the next couple days and let you know whether there are any issues still present or not.

**Comment by BLOKBUSTR** [comment]
I tested the datapack on 1.20.1, since Create and its addons aren't available on 1.21 yet. The "New Recipes Unlocked!" toast still appears, but I guess it shouldn't be too big of a deal as the recipes themselves work completely fine, even with Steam 'n' Rails' custom minecarts.

**Comment by Itsyourdriver** [comment]
> I tested the datapack on 1.20.1, since Create and its addons aren't available on 1.21 yet. The "New Recipes Unlocked!" toast still appears, but I guess it shouldn't be too big of a deal as the recipes themselves work completely fine, even with Steam 'n' Rails' custom minecarts.

I can probably stop clearing the recipe from players (which will fix the toast from showing every time) because I also swapped the advancement to use recipe_crafted instead of recipe_unlocked.
